### ISSUE TITLE
I find the mention of BLM and defund the police as unnecessary and irrelevant

### ISSUE THREAD

**Issue by iJynx** [fabacab/awesome-cybersecurity-blueteam#14]
I don't know why you had to introduce BLM or defundthepolice into this, it's an awesome list not your local liberal board. Why are you like this?

**Comment by RashadWilkins** [comment]
Honestly, I just fork my own and remove the banner and stuff then send that to whoever needs it. I already know anything that I could or would say would be overlooked or argued with. At this point, I am just in a state of uncaring.

**Comment by fabacab** [comment]
> I don't know why you had to introduce BLM or defundthepolice into this

I don't care.

> it's an awesome list not your local liberal board.

Thanks.
